language: android
sudo: false
jdk:
  - oraclejdk8
android:
  components:
    - build-tools-25.0.2
    - android-25
    - extra-android-support
    - extra-android-m2repository
  licenses:
    - 'android-sdk-license-.+'
    - '.*intel.+'
before_install:
  - chmod +x gradlew
install:
  - ./gradlew
script:
  - ./gradlew :library:build
  - ./gradlew :sample:build
